application/urls.py
from django.conf import settings
from django.conf.urls import (
    include,
    patterns,
    url
)
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = patterns(
        '',
        url(r'^admin/', include(admin.site.urls)),
        url(r'^i18n/', include('django.conf.urls.i18n')),
        url(r'^', include('nalch_application.urls')),
)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

nalch_application/urls.py
from django.conf.urls import url

from views import (
    areasofexpertise,
    areasofinterest,
    contact,
    index,
    references
)


urlpatterns = [
    url(r'^(?P<applicant>[a-z]+)/$', index, name='index'),
    url(r'^(?P<applicant>[a-z]+)/references/(?P<reference>\w+)?/?$', references, name='references'),
    url(r'^(?P<applicant>[a-z]+)/contact/$', contact, name='contact'),
    url(r'^(?P<applicant>[a-z]+)/areasofinterest/$', areasofinterest, name='areasofinterest'),
    url(r'^(?P<applicant>[a-z]+)/areasofexpertise/$', areasofexpertise, name='areasofexpertise')
]

nalch_application/models.py
from colorful.fields import RGBColorField

from django.contrib.auth.models import User
from django.db import models
from django.utils.translation import ugettext_lazy as _

from . import app_settings


class TranslatableNameMixin(models.Model):
    name_id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=200, unique=True)

    def __unicode__(self):
        return self.name

    class Meta:
        abstract = True


class IconMixin(models.Model):
    icon = models.CharField(
        default='',
        choices=[(icon, _(icon)) for icon in app_settings.ICONS.keys()],
        max_length=200,
        help_text='a bootstrap or font awesome icon'
    )

    class Meta:
        abstract = True


class Tag(TranslatableNameMixin, IconMixin):
    color = RGBColorField()


class Technology(TranslatableNameMixin, IconMixin):
    pass


class TagnologyMixin(models.Model):
    tags = models.ManyToManyField(Tag, blank=True, null=True)
    technologies = models.ManyToManyField(Technology, blank=True, null=True)

    class Meta:
        abstract = True


class Group(TranslatableNameMixin):
    description = models.TextField()
    short_name = models.CharField(max_length=25, unique=True)

    @property
    def public_name(self):
        return self.short_name_en


class AreaMixin(TranslatableNameMixin, TagnologyMixin):
    description = models.TextField()
    order = models.PositiveIntegerField(default=0, blank=False, null=False)

    class Meta(object):
        abstract = True
        ordering = ('order', )


class AreaOfInterest(AreaMixin):
    pass


class AreaOfKnowledge(AreaMixin):
    pass


class Applicant(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    birthday = models.DateField(blank=True, null=True)
    address = models.TextField(blank=True, null=True)
    profile_picture = models.ImageField(blank=True, null=True)
    template = models.CharField(
            blank=True,
            null=True,
            max_length=250,
            default='photon',
            choices=[(template, _(template)) for template in app_settings.TEMPLATES],
    )

    areas_of_interest = models.ManyToManyField(AreaOfInterest, blank=True, null=True, related_name='interests')
    areas_of_expertise = models.ManyToManyField(AreaOfKnowledge, blank=True, null=True, related_name='expertises')

    @property
    def contact_links(self):
        return self.contactdetail_set.filter(link=True)

    def __unicode__(self):
        return self.user.username


class Description(IconMixin):
    description = models.TextField()

    user = models.OneToOneField(Applicant)


class Project(TranslatableNameMixin):
    """
    model to represent projects with names, descriptions, images and tags
    """
    short_name = models.CharField(max_length=25, unique=True)
    short_description = models.TextField(max_length=255, default='')
    description = models.TextField()
    title_thumbnail = models.ImageField()
    publish = models.BooleanField(default=True)
    groups = models.ManyToManyField(Group)

    technologies = models.ManyToManyField(Technology, blank=True, null=True)

    user = models.ForeignKey(Applicant)

    order = models.PositiveIntegerField(default=0, blank=False, null=False)

    @property
    def public_name(self):
        return self.short_name_en

    @property
    def icons(self):
        return self.technologies.filter(icon__in=app_settings.FONTICONS)

    class Meta(object):
        ordering = ('order',)


class Attachment(TranslatableNameMixin):
    file = models.FileField()
    project = models.ForeignKey(Project)


class ProjectImage(TranslatableNameMixin):
    project = models.ForeignKey(Project, related_name='images')
    image = models.ImageField()
    thumbnail = models.ImageField()


class ContactDetail(TranslatableNameMixin, IconMixin):
    applicant = models.ForeignKey(Applicant, blank=True, null=True)
    link = models.BooleanField(default=False)

    def __unicode__(self):
        return '%s: %s' % (self.applicant, self.name)


class KnowledgeLevel(IconMixin):
    weight = models.CharField(
        default='',
        choices=[
            ('basic', _('basic knowledge')),
            ('working', _('working knowledge')),
            ('advanced', _('advanced knowledge')),
        ],
        max_length=200,
    )

    def __unicode__(self):
        return self.weight


class WeightedTag(models.Model):
    tag = models.ForeignKey(Tag)
    weight = models.ForeignKey(KnowledgeLevel)
    project = models.ForeignKey(Project, blank=True, null=True)

    def __unicode__(self):
        return '%s@%s' % (self.tag.name, self.weight)

nalch_application/views.py
from django.http import HttpResponse
from django.shortcuts import (
    get_object_or_404,
    render_to_response
)
from django.template import RequestContext
# for future use
# from django.template.loader import select_template

from itertools import chain


from nalch_application.models import (
    Applicant,
    Project,
)


def get_shared_context(request, applicant, active='index'):
    """
    collects common information about an applicant and stores them in the context
    Information:
        active -> active page
        applicant -> current applicant
        references -> the applicant's published references
    :param request: HTTPRequest
    :type request: HttpRequest
    :param applicant: the current applicant's name
    :type applicant: str
    :param active: active page, default: index
    :type active: str
    :return: the common context (keys: active, applicant, references)
    :rtype: dict
    """
    get_object_or_404(Applicant, user__username=applicant)
    projects = Project.objects.filter(publish=True, user__user__username=applicant)
    # get all groups for all references, flatten the list using itertools and remove duplicates
    groups = set(chain.from_iterable([reference.groups.all() for reference in projects]))
    # group references -> references: { group1: [reference1, reference2, ...], group2: [...], ...}
    references = {
        group: [reference for reference in projects if group in reference.groups.all()] for group in groups
    }
    context = {
        'active': active,
        'applicant': Applicant.objects.get(user__username=applicant),
        'references': references,
    }
    return context


def index(request, applicant):
    """
    render index view with common context. Template is application/<applicant.template>/index.html or the default
    application/index.html
    :param request: HTTPRequest
    :type request: HttpRequest
    :param applicant: The current applicant
    :type applicant: str
    :return: rendered template as HttpResponse
    :rtype: HttpResponse
    """
    # for future use:
    #   template = select_template(['application/%s/index.htm' % applicant.template, 'application/index.html'])
    context = get_shared_context(request, applicant)
    return render_to_response(
            'application/%s/index.html' % context['applicant'].template,
            context,
            context_instance=RequestContext(request)
    )


def contact(request, applicant):
    """
    render contact view with common context. Template is application/<applicant.template>/contact.html or the default
    application/contact.html
    :param request: HTTPRequest
    :type request: HttpRequest
    :param applicant: The current applicant
    :type applicant: str
    :return: rendered template as HttpResponse
    :rtype: HttpResponse
    """
    context = get_shared_context(request, applicant, 'contact')
    return render_to_response(
            'application/%s/contact.html' % context['applicant'].template,
            context,
            context_instance=RequestContext(request)
    )


def references(request, applicant, reference):
    """
    render reference view with common context and a current detailed reference.
    Template is application/<applicant.template>/references.html or the default application/references.html
    :param request: HTTPRequest
    :type request: HttpRequest
    :param applicant: The current applicant
    :type applicant: str
    :param reference: The current reference project
    :type reference: Project
    :return: rendered template as HttpResponse
    :rtype: HttpResponse
    """
    context = get_shared_context(request, applicant, 'references')
    current_ref = Project.objects.filter(publish=True, user__user__username=applicant, short_name_en=reference).first()
    if current_ref is None:
        current_ref = Project.objects.filter(publish=True, user__user__username=applicant).first()
    context.update(
        {
            'current_reference': current_ref
        }
    )
    return render_to_response(
        'application/%s/references.html' % context['applicant'].template,
        context,
        context_instance=RequestContext(request)
    )


def areasofinterest(request, applicant):
    """
    render areasofinterest view with common context and the applicant's areas of interest (key: areas).
    Template is application/<applicant.template>/areas.html or the
    default application/areas.html
    :param request: HTTPRequest
    :type request: HttpRequest
    :param applicant: The current applicant
    :type applicant: str
    :return: rendered template as HttpResponse
    :rtype: HttpResponse
    """
    context = get_shared_context(request, applicant, 'areasofinterest')
    context.update(
            {
                'areas': get_object_or_404(Applicant, user__username=applicant).areas_of_interest.all()
            }
    )
    return render_to_response(
            'application/%s/areas.html' % context['applicant'].template,
            context,
            context_instance=RequestContext(request)
    )


def areasofexpertise(request, applicant):
    """
    render areasofexpertise view with common context and the applicant's areas of expertise (key: areas).
    Template is application/<applicant.template>/areas.html or the
    default application/areas.html
    :param request: HTTPRequest
    :type request: HttpRequest
    :param applicant: The current applicant
    :type applicant: str
    :return: rendered template as HttpResponse
    :rtype: HttpResponse
    """
    context = get_shared_context(request, applicant, 'areasofexpertise')
    context.update(
            {
                'areas': get_object_or_404(Applicant, user__username=applicant).areas_of_expertise.all()
            }
    )
    return render_to_response(
            'application/%s/areas.html' % context['applicant'].template,
            context,
            context_instance=RequestContext(request)
    )

nalch_application/templates/application/templatetags/reference.html
{% load i18n %}

<div id="{{ group.public_name }}-{{ reference.public_name }}" class="container spacey">

  <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title"><b>{{ reference.name }}</b></h3>
        </div>
        <div class="panel-body">
            <div class="row">
                <div class="col-md-3"><img data-src="holder.js/200x200" src="{{ reference.title_thumbnail.url }}" class="img-full" alt="Logo"/></div>
                <div class="col-md-9">
                    {{ reference.description|safe }}

                    {% if reference.attachment_set.all|length > 0 %}
                        <br/><br/>
                        {% trans 'Attachments' %}
                        <ul>
                            {% for attachment in reference.attachment_set.all %}
                                <li><a href="{{ attachment.file.url }}">{{ attachment.name }}</a> ({{ attachment.file.size|filesizeformat }})</li>
                            {% endfor %}
                        </ul>
                    {% endif %}

                    <hr/>

                    {% if reference.weightedtag_set.all|length > 0 %}
                        {% trans 'Tags' %}<br/>
                        {% for weighted_tag in reference.weightedtag_set.all %}
                            <span class="label" style="background: {{ weighted_tag.tag.color }}">{{ weighted_tag.tag }}</span>
                        {% endfor %}
                        <br/>
                        <br/>
                    {% endif %}

                    {% if reference.technologies.all|length > 0 %}
                        {% trans 'Technologies' %}<br/>
                        <ul>
                        {% for tech in reference.technologies.all %}
                            <li>{{ tech }}</li>
                        {% endfor %}
                        </ul>
                    {% endif %}
                </div>
          </div>
          <div class="row">
                    <div id="{{ group.public_name }}-{{ reference.public_name }}-gallery" class="gallery spacey center">
                        {% for image in reference.images.all %}
                        <a href="{{ image.image.url }}" title="{{ image.title }}"><img src="{{ image.thumbnail.url }}" alt="{{ image.title }}"/></a>
                        {% endfor %}
                    </div>
          </div>
        </div>
      </div>

</div>

nalch_application/templates/application/templatetags/reference_table.html
{% load i18n reference_extras %}

<table id="references" class="center spacey table table-striped">
<caption class="spacey">
    {% for level in knowledge_level %}
        <div class="legend"><span class="glyphicon glyphicon-{{ level.icon }}"></span>{{ level.get_weight_display }}</div>
    {% endfor %}
</caption>
<tr>
    <th>{% trans 'Group' %}</th>
    <th>{% trans 'Project' %}</th>
    {% for tag in tags %}
        <th>{{ tag.name }}</th>
    {% endfor %}
</tr>
{% for group, grouped_references in references.iteritems %}
    {% for reference in grouped_references %}
        <tr>
          {% if forloop.first %}
              <td rowspan="{{ grouped_references|length }}" class="reference_group">{{ group.name }}</td>
          {% endif %}
          <td><a href="#{{ group.public_name }}-{{ reference.public_name }}">{{ reference.short_name }}</a></td>
          {% for tag in tags %}
            <td><div class="glyphicon glyphicon-{% knowledge_level tag reference %} center"></div></td>
          {% endfor %}
        </tr>
    {% endfor %}
{% endfor %}
</table>

nalch_application/templates/application/templatetags/small_reference.html
{% load i18n %}

<div id="{{ reference.public_name }}" class="container spacey">

  <div class="panel panel-default">
        <div class="panel-heading">
          <h3 class="panel-title"><b>{{ reference.name }}</b></h3>
        </div>
        <div class="panel-body">
            <div class="row">
                <div class="col-md-12">
                    {{ reference.description|safe }}

                    <hr/>

                    {% if reference.tags.all|length > 0 %}
                        {% trans 'Tags' %}<br/>
                        {% for tag in reference.tags.all %}
                            <span class="label" style="background: {{ tag.color }}">{{ tag }}</span>
                        {% endfor %}
                        <br/>
                        <br/>
                    {% endif %}

                    {% if reference.technologies.all|length > 0 %}
                        {% trans 'Technologies' %}<br/>
                        <ul>
                        {% for tech in reference.technologies.all %}
                            <li>{{ tech }}</li>
                        {% endfor %}
                        </ul>
                    {% endif %}
                </div>
          </div>
        </div>
      </div>

</div>